spring:
  application:
    name: springboot-service
  security:
    user:
      name: user
      password: Admin@123
  datasource:
    url: jdbc:mysql://localhost:13306/xywl_online_1?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    hikari: # 使用hikari 连接池
      maximumPoolSize: 15
      minimumIdle: 5
      idleTimeout: 30000
      connectionTimeout: 30000
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
      poolName: DatebookHikariCP
      autoCommit: true
server:
  port: 9023
  servlet:
    context-path: /
  ssl:
    enable: true
    key-store: classpath:key/website_a.jks
    key-password: Admin@1234
    key-store-type: JKS
    key-store-password: Admin@123